"""add ticket timer session and draft note fields

Revision ID: 05d87abee0c7
Revises: 625c312074ff
Create Date: 2026-08-14 14:04:39.447003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d87abee0c7'
down_revision: Union[str, Sequence[str], None] = '625c312074ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('timer_start_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('timer_base_seconds', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tickets', sa.Column('last_note_marker_seconds', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tickets', sa.Column('draft_note_desc', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('draft_note_billable', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tickets', sa.Column('draft_note_catalogue_item_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'catalogue_items', ['draft_note_catalogue_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'draft_note_catalogue_item_id')
    op.drop_column('tickets', 'draft_note_billable')
    op.drop_column('tickets', 'draft_note_desc')
    op.drop_column('tickets', 'last_note_marker_seconds')
    op.drop_column('tickets', 'timer_base_seconds')
    op.drop_column('tickets', 'timer_start_at')
    # ### end Alembic commands ###
