"""cdr_report_schedules

Revision ID: 3792331071d9
Revises: 05d87abee0c7
Create Date: 2026-08-19 13:26:53.699950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3792331071d9'
down_revision: Union[str, Sequence[str], None] = '05d87abee0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdr_report_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('frequency_type', sa.String(length=20), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('send_hour', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cdr_report_run_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('triggered_manually', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['cdr_report_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # NOTE : autogenerate detectait aussi la suppression de 2 index sans
    # rapport (ix_appointments_start_at, ix_email_opens_entity) -- drift
    # pre-existant, retire d'ici volontairement (pas dans le scope de
    # TASK-032.2, voir feedback_no_unrequested_deletion).


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cdr_report_run_logs')
    op.drop_table('cdr_report_schedules')
    # ### end Alembic commands ###
