"""add_company_account_number

Revision ID: 4ea01ffaadb0
Revises: 9878b98f97d8
Create Date: 2026-06-28 00:32:32.210670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea01ffaadb0'
down_revision: Union[str, Sequence[str], None] = '9878b98f97d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('account_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'account_number')
    # ### end Alembic commands ###
