"""add oauth client credentials to cloud backup connections

Revision ID: 625c312074ff
Revises: 4f9df349c341
Create Date: 2026-08-13 18:29:07.474007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625c312074ff'
down_revision: Union[str, Sequence[str], None] = '4f9df349c341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_backup_connections', sa.Column('client_id', sa.String(length=255), nullable=True))
    op.add_column('cloud_backup_connections', sa.Column('client_secret_enc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_backup_connections', 'client_secret_enc')
    op.drop_column('cloud_backup_connections', 'client_id')
    # ### end Alembic commands ###
