"""extend_company_fiscal_fields

Revision ID: 9878b98f97d8
Revises: c3a7edbc7bc7
Create Date: 2026-06-28 00:30:58.922580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9878b98f97d8'
down_revision: Union[str, Sequence[str], None] = 'c3a7edbc7bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('neq', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('shareholder_type', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('employee_count', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('annual_revenue', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('internal_manager_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('companies', sa.Column('exchange_rate', sa.Float(), nullable=False))
    op.add_column('companies', sa.Column('is_taxable', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('tax_country', sa.String(length=2), nullable=False))
    op.add_column('companies', sa.Column('tax_province', sa.String(length=2), nullable=False))
    op.add_column('companies', sa.Column('tps_rate', sa.Float(), nullable=False))
    op.add_column('companies', sa.Column('tvq_rate', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'companies', 'users', ['internal_manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'tvq_rate')
    op.drop_column('companies', 'tps_rate')
    op.drop_column('companies', 'tax_province')
    op.drop_column('companies', 'tax_country')
    op.drop_column('companies', 'is_taxable')
    op.drop_column('companies', 'exchange_rate')
    op.drop_column('companies', 'currency')
    op.drop_column('companies', 'internal_manager_id')
    op.drop_column('companies', 'annual_revenue')
    op.drop_column('companies', 'employee_count')
    op.drop_column('companies', 'shareholder_type')
    op.drop_column('companies', 'neq')
    # ### end Alembic commands ###
