"""add_users

Revision ID: c3a7edbc7bc7
Revises: e045c84fb709
Create Date: 2026-06-27 23:56:03.986779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a7edbc7bc7'
down_revision: Union[str, Sequence[str], None] = 'e045c84fb709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'tech', 'billing', 'readonly', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_unique_constraint(None, 'contact_company_functions', ['contact_company_id', 'function_id'])
    op.create_unique_constraint(None, 'entity_statuses', ['entity_id', 'status_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entity_statuses', type_='unique')
    op.drop_constraint(None, 'contact_company_functions', type_='unique')
    op.drop_table('users')
    # ### end Alembic commands ###
